### ISSUE TITLE
StreetEasy: Filter new input data for streeteasy_weekly_nta

### ISSUE THREAD

**Issue by mgraber** [MODA-NYC/db-recovery-data-partnership#160]
Input data now has a field `No. of bedrooms`. Filter to `No. of bedrooms = 'All'`

## Tasks required
Same tasks as necessary for #161

- [x] Edit [initialization script](https://github.com/MODA-NYC/db-recovery-data-partnership/blob/9c4cf6bcbc7eff63c43d7d549d93354a70850fc7/recipes/street_easy/init.sql#L16-L37) to account for the new source data schema.
- [x] Check to see if source data location has changed, and edit [download step](https://github.com/MODA-NYC/db-recovery-data-partnership/blob/9c4cf6bcbc7eff63c43d7d549d93354a70850fc7/recipes/street_easy/runner.sh#L32) if necessary.
- [x] Modify create statement in [create.sql](https://github.com/MODA-NYC/db-recovery-data-partnership/blob/master/recipes/street_easy/create.sql) to account for new column.
- [x] In  [create.sql](https://github.com/MODA-NYC/db-recovery-data-partnership/blob/master/recipes/street_easy/create.sql), split input table into a table including only `numrooms='All'` and a table excluding `numrooms=All`.
- [x] Export the two tables as `streeteasy_weekly_nta` and `streeteasy_weekly_nta_by_rooms` respectively, using the same technique as in [these lines](https://github.com/MODA-NYC/db-recovery-data-partnership/blob/9c4cf6bcbc7eff63c43d7d549d93354a70850fc7/recipes/street_easy/runner.sh#L45-L57).

**Comment by SPTKL** [comment]
init script will be phased out
