### ISSUE TITLE
StreetEasy: Create streeteasy_weekly_nta_by_rooms

### ISSUE THREAD

**Issue by mgraber** [MODA-NYC/db-recovery-data-partnership#161]
## Tasks required
Same tasks as necessary for #160

- [x] Edit [initialization script](https://github.com/MODA-NYC/db-recovery-data-partnership/blob/9c4cf6bcbc7eff63c43d7d549d93354a70850fc7/recipes/street_easy/init.sql#L16-L37) to account for the new source data schema.
- [x] Check to see if source data location has changed, and edit [download step](https://github.com/MODA-NYC/db-recovery-data-partnership/blob/9c4cf6bcbc7eff63c43d7d549d93354a70850fc7/recipes/street_easy/runner.sh#L32) if necessary.
- [x] Modify create statement in [create.sql](https://github.com/MODA-NYC/db-recovery-data-partnership/blob/master/recipes/street_easy/create.sql) to account for new column.
- [x] In  [create.sql](https://github.com/MODA-NYC/db-recovery-data-partnership/blob/master/recipes/street_easy/create.sql), split input table into a table including only `numrooms='All'` and a table excluding `numrooms=All`.
- [ ] Export the two tables as `streeteasy_weekly_nta` and `streeteasy_weekly_nta_by_rooms` respectively, using the same technique as in [these lines](https://github.com/MODA-NYC/db-recovery-data-partnership/blob/9c4cf6bcbc7eff63c43d7d549d93354a70850fc7/recipes/street_easy/runner.sh#L45-L57).

## Target schema
| Input field name | Data Type   | Output field name | Output example |
|------------------|-------------|-------------------|----------------|
| Week Start Date     | `IYYY-IW` |     year_week     |  2020-30   |
| NTA Name             | `text`    |        ntaname        | Allerton-Pelham Gardens    |
| NTA Code     | `varchar(4)` |     ntacode     | BX31     |
|     | `text` |     borough     | BX     |
|     | `int` |     borocode    | 1     |
| No. of bedrooms  | `text` | numrooms | Studio |
| No. of New Sale Listings     | `int` |     s_newlist     |  3     |
| No. of Pending Sale Listings     | `int` |     s_pendlist    |  3     |
| No. of Sale Listings     | `int` |     s_list     |  3     |
| Pct Hike (Sales)     | `double precision` |     s_pct_inc      |  5.01   |
| Pct Cut (Sales)     | `double precision` |     s_pct_dec     |  5.26     |
| Median Weeks on Market (Sales)     | `double precision` |     s_wksonmkt     |  14.0     |
| No. of New Rental Listings     | `int` |      r_newlist    |  3     |
| No. of Pending Listings     | `int` |    r_pendlist      |  3     |
| No. of Rental Listings     | `int` |    r_list     |  3     |
| Pct Hike (Rentals)     | `double precision` |    r_pct_inc      |  5.01   |
| Pct Cut (Rentals)     | `double precision` |      r_pct_dec    |  5.26    |
| Pct Furnished (Rentals)     | `double precision` |    r_pct_furn      | 1.47   |
| Pct Short Term (Rentals)     | `double precision` |   r_pct_shot      |  0.09   |
| Pct with Concessions (Rentals)     | `double precision` |    r_pct_con     |  3.70   |
| Median Weeks on Market (Rentals)     | `double precision` |    r_wksonmkt     |  14.1     |
