### ISSUE TITLE
StreetEasy: Get borough level index from new input table

### ISSUE THREAD

**Issue by mgraber** [MODA-NYC/db-recovery-data-partnership#162]
## Tasks required
- [ ] All tasks in #163
- [ ] Create a new table/view in [create_rental_sales_index.sql](https://github.com/MODA-NYC/db-recovery-data-partnership/blob/master/recipes/street_easy/create_rental_sales_index.sql) that contains only borough-level data. This would be instances where the borough name and the submarket name are the same.
- [ ] Export new borough-level table/view using methods in [these lines](https://github.com/MODA-NYC/db-recovery-data-partnership/blob/9c4cf6bcbc7eff63c43d7d549d93354a70850fc7/recipes/street_easy/runner.sh#L75-L77).
