### ISSUE TITLE
StreetEasy: Create streeteasy_monthly_rental_sales_index_submkt

### ISSUE THREAD

**Issue by mgraber** [MODA-NYC/db-recovery-data-partnership#163]
Create new table streeteasy_monthly_rental_sales_index_submkt

## Tasks required
- [x] Update source data location in [these lines](https://github.com/MODA-NYC/db-recovery-data-partnership/blob/9c4cf6bcbc7eff63c43d7d549d93354a70850fc7/recipes/street_easy/build_rental_sales_index.py#L5-L6)
- [x] Data is now unpivoted and merged, so we no longer need to perform [these lines](https://github.com/MODA-NYC/db-recovery-data-partnership/blob/9c4cf6bcbc7eff63c43d7d549d93354a70850fc7/recipes/street_easy/build_rental_sales_index.py#L15-L29). Instead, we need to separate the sales and rental data and then join to each other on submarket name.
- [x] Update [create_rental_sales_index.sql](https://github.com/MODA-NYC/db-recovery-data-partnership/blob/master/recipes/street_easy/create_rental_sales_index.sql) to reflect new input schema, and to include the submarket in the [table definition](https://github.com/MODA-NYC/db-recovery-data-partnership/blob/9c4cf6bcbc7eff63c43d7d549d93354a70850fc7/recipes/street_easy/create_rental_sales_index.sql#L14-L34).
- [x] Create a view of the table that only contains submarkets, and not borough-level data. These would be the records where the name of the submarket is not the same as the name of the borough.
- [x] Export the new view as streeteasy_monthly_rental_sales_index_submkt by modifying [these lines](https://github.com/MODA-NYC/db-recovery-data-partnership/blob/9c4cf6bcbc7eff63c43d7d549d93354a70850fc7/recipes/street_easy/runner.sh#L74-L77) to account for new table name.
- [x] Fix the previous workflow to create streeteasy_monthly_rental_sales_index, which we will now call streeteasy_monthly_rental_sales_index_boro. See issue #162.

## Target schema
| Input field name | Data Type   | Output field name | Output example |
|------------------|-------------|-------------------|----------------|
| Month     | `YYYY-MM` |     year_month     |  2020-07   |
| Borough    | `varchar(2)` |     borough     |  MN   |
| Borough    | `int` |     borocode     |  1   |
| NAME | `text` | submarket | East Brooklyn |
| Sales Index    | `double precision` |     sales_index     |  620106  |
| Rental Index    | `double precision` |     rental_index     |  2683  |

**Comment by objornsson** [comment]
@mgraber @SteveScott @WillHsiao In [street_easy/latest](nyccityhall.sharepoint.com/sites/RDPDataRepository/street_easy/Forms/AllItems.aspx?viewid=7c35811c-08ee-4d21-8df3-d5148fabc581&id=%2Fsites%2FRDPDataRepository%2Fstreet_easy%2Flatest) on SharePoint, I see both _streeteasy_monthly_rental_sales_index_ and _streeteasy_monthly_rental_sales_index_boro_. Is removing one of these files from the pipeline an outstanding item?

**Comment by SPTKL** [comment]
@objornsson those files would need to be hand deleted, it's already done
![image](https://user-images.githubusercontent.com/13207770/102359932-669e9f00-3f7f-11eb-95a2-5e7d6a8c5828.png)

please double check and close out this issue when everything is ready

**Comment by objornsson** [comment]
@SPTKL thanks for following up, yes, it's now resolved
